---
title: STAT 4194 Project
author:
- Andre Contreras
- Jiayi Gao
- Mitch Krenz
- Paarth Mahajan
- Tony Zheng
format:
    revealjs:
        smaller: true
    pptx:
        fig-format: "svg"
execute:
    echo: false
    cache: true
    autodep: true
---

# Packages Used

```{r}
#| label: libraries
library(tidyverse)
library(igraph)
library(rgexf)
```

# Data

```{r}
# label: Data Setup
dir.create("data", showWarnings = FALSE)
base_url <- "https://raw.githubusercontent.com/tzheng7679/STAT-4194-Project/main/data/"

# Specific sample of 20 movies
movies_sample <- read_tsv(I("id\ttitle\n488\tThe Last Samurai\n682\tReservoir Dogs\n130\tBlack Rain\n134\tBlade Runner\n671\tThe Reader\n843\tTRON\n495\tLeviathan\n41\tAlien: Resurrection\n816\tThirteen Days\n227\tThe Crying Game\n511\tLord of Illusions\n791\tSugar & Spice\n487\tThe Last of the Mohicans\n217\tCrank\n116\tBeing Human\n471\tThe King's Speech\n189\tChasing Sleep\n244\tDeath to Smoochy\n320\tFrench Kiss\n214\tCoraline"))
```

# ER Model

{{< include er.qmd >}}

# Chung-Lu Model

{{< include "4194C Chung Lu Model.qmd" >}}

# Spectral Model

{{< include spectral_slides.qmd >}}

# AME

{{< include ame.qmd >}}